name: Python CI/CD

on:
  push:
    branches:
      - main

env:
  POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
  SECRET_KEY: ${{ secrets.SECRET_KEY }}
  HOST_NAME: ${{ vars.HOST_NAME }}

jobs:
  test:

    runs-on: ubuntu-latest

    services:
        postgres:
          image: postgres:latest
          env:
            POSTGRES_DB: carParser
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: ${{ env.POSTGRES_PASSWORD }}
          ports:
            - 5432:5432

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest

    - name: Run tests
      run: |
        pytest app_test.py -v

  deploy:
    runs-on: ubuntu-latest
    needs: test

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Deploy to server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd carParserProjectTest/Car-parser-project-back
          docker-compose down
          git pull origin main
          docker-compose up --build -d
          echo "done"